name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  # Lint:
  # Lint任务
  UnitTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16.x
      - uses: pnpm/action-setup@v3
        with:
          node-version: 16.x
          version: 7.0.1
      - name: Install modules
        run: pnpm install
      - name: Run Test
        run: pnpm run test:run
